version: "3.7"

services:
  samba:
    image: khanguyentuan/samba
    ports:
      - 139:139
      - 445:445
    environment:
      smbuser: smbuser
      password: 1234567
    volumes:
      - /home/data:/data # make sure to have /home/data folder in all of nodes
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role==manager

  service1:
    depends_on:
      - samba
    image: khanguyentuan/swarmtest:node
    networks:
      - net2
    ports:
      - 8085:8085
    volumes:
      - vol2:/d2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure

  service2:
    depends_on:
      - samba
    image: khanguyentuan/swarmtest:php
    networks:
      - net2
    ports:
      - 8086:8085
    volumes:
      - vol1:/d1/
      - vol2:/d2/
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure
  
  proxy:
    depends_on:
      - service1
      - service2
    image: khanguyentuan/nginx
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure
    networks:
      - net2
        
networks:
  net1: # default overlay
  net2:
    driver: overlay
    name: www-net2

volumes:
  vol1: # local volume
    driver: local
    name: v1
    driver_opts:
      type: none
      device: "/home/"
      o: bind

  vol2: 
    driver: local
    name: v2
    driver_opts:
      type: cifs
      device: //SWARM_IP/data/
      o: username=smbuser,password=1234567,file_mode=0777,dir_mode=0777,vers=3.0,sec=ntlmssp