name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Download Docker Info from S3 Bucket
        run: |
          aws s3 cp s3://kha-app-s3/swarm_info/swarm_info.txt .
      - name: Delete Docker Info on S3 bucket
        run: |
          aws s3 rm s3://kha-app-s3/swarm_info/swarm_info.txt
      - name: Read envs from CI
        id: read_swarm_info
        run: |
          SWARM_INFO=$(cat ./swarm_info.txt)
          IFS=',' read -ra ADDR <<< "$SWARM_INFO"
          SWARM_IP=${ADDR[0]}
          SWARM_USER=${ADDR[1]}
          echo "SWARM_IP=$SWARM_IP" >> $GITHUB_ENV
          echo "SWARM_USER=$SWARM_USER" >> $GITHUB_ENV
      - name: Deploy
        run: bash ./deploy/deploy.sh ${{env.SWARM_IP}} ${{env.SWARM_USER}} "${{secrets.SSH_PRIVATE_KEY}}"