name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Download Docker Info from S3 Bucket
        run: |
          aws s3 cp s3://kha-app-s3/swarm_info/swarm_info.txt .
      - name: Delete Docker Info on S3 bucket
        run: |
          aws s3 rm s3://kha-app-s3/swarm_info/swarm_info.txt
      - name: Read envs from CI
        id: read_swarm_info
        run: |
          SWARM_INFO=$(cat ./swarm_info.txt)
          IFS=',' read -ra ADDR <<< "$SWARM_INFO"
          SWARM_IP=${ADDR[0]}
          SWARM_USER=${ADDR[1]}
          echo "SWARM_IP=$SWARM_IP" >> $GITHUB_ENV
          echo "SWARM_USER=$SWARM_USER" >> $GITHUB_ENV
      - name: Deploy
        run: |
          SWARM_IP=${{env.SWARM_IP}}
          SWARM_USER=${{env.SWARM_USER}}
          SSH_PRIVATE_KEY="${{secrets.SSH_PRIVATE_KEY}}"
          DEPLOY_FILE=docker-compose.yml
          STACK_NAME=t1
          echo "/-\|/-\|/-\|/-\|/-\|/-\|/-\|"
          echo $SSH_PRIVATE_KEY
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -i ~/.ssh/id_rsa ./deploy/$DEPLOY_FILE $SWARM_USER@$SWARM_IP:/home/ubuntu
          ssh -tt -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SWARM_USER@$SWARM_IP "sudo docker stack deploy -c /home/ubuntu/$DEPLOY_FILE $STACK_NAME"
          echo "Deploy successfully"