name: CI

on:
  push:
    branches:
      - main

env:
  BE_SERVICE: swarmtest
  NGINX_SERVICE: nginx
  SMB_SERVICE: samba

jobs:
  apply_terraform:
    # needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Initialize Terraform
        run: terraform init
      - name: Apply Terraform
        run: terraform apply -auto-approve
      - name: Copy Terraform State to S3 Bucket
        run: |
          aws s3 cp terraform.tfstate s3://kha-app-s3/state/
      - name: Get IPs of instances
        run: |
          ips=$(terraform output -json | jq -r '.instance_ips.value | join(",")')
          echo "::set-output name=public_ips::$ips"
      - name: Add SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
  init_swarm:
    needs: apply_terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Add SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      - name: Init Docker Swarm On Instance 1
        id: init_swarm
        run: |
          IPS="${{ needs.apply_terraform.outputs.public_ips }}"
          IFS=',' read -ra ADDR <<< "$IP"
          SWARM_IP=${ADDR[0]}
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$SWARM_IP << 'EOF'
            sudo apt-get update
            sudo apt-get install docker.io -y
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo docker swarm init --advertise-addr=$SWARM_IP
          EOF
          JOIN_TOKEN=$(ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$SWARM_IP "sudo docker swarm join-token -q worker")
          echo "::set-output join_token=$JOIN_TOKEN"
          echo "::set-output swarm_ip=$SWARM_IP"
  join-swarm:
    needs: init_swarm
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      - name: Instance 2 joins Docker Swarm
        run: |
          IPS="${{ needs.apply_terraform.outputs.public_ips }}"
          IFS=',' read -ra ADDR <<< "$IP"
          SWARM_IP=${ADDR[0]}
          JOIN_IP=${ADDR[1]}
          JOIN_TOKEN="${{ needs.init_swarm.outputs.join_token }}"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$JOIN_IP << EOF
            sudo apt-get update
            sudo apt-get install docker.io -y
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo docker swarm join --token $JOIN_TOKEN $SWARM_IP:2377
          EOF