name: CI

on:
  push:
    branches:
      - main

env:
  BE_SERVICE: swarmtest
  NGINX_SERVICE: nginx
  SMB_SERVICE: samba

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build And Push Docker Images
        env:
          REGISTRY: ${{ secrets.DOCKER_USERNAME }}
        run: |-
          docker build -t $REGISTRY/$BE_SERVICE:node -f Dockerfile ./node
          docker push $REGISTRY/$BE_SERVICE:node
          docker build -t $REGISTRY/$BE_SERVICE:php -f Dockerfile ./php
          docker push $REGISTRY/$BE_SERVICE:php
          docker build -t $REGISTRY/$SMB_SERVICE -f Dockerfile ./samba
          docker push $REGISTRY/$SMB_SERVICE
          docker build -t $REGISTRY/$NGINX_SERVICE -f Dockerfile ./nginx
          docker push $REGISTRY/$NGINX_SERVICE