name: CI

on:
  push:
    branches:
      - main

jobs:
 
  join-swarm:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Instance 2 joins Docker Swarm
        run: |
          IPS="13.212.76.134,13.212.190.63"
          IFS=',' read -ra ADDR <<< "$IPS"
          SWARM_IP=${ADDR[0]}
          JOIN_IP=${ADDR[1]}
          JOIN_TOKEN="SWMTKN-1-61xxxlnoomt3k41nsptvvj514h54rc87zyjfhpradci1r02i62-ak2qhfr8d3bxp0keysglvtena"
          echo "$JOIN_TOKEN"
          echo "$JOIN_IP"
          echo "$SWARM_IP"
          echo "sudo docker swarm join --token $JOIN_TOKEN $SWARM_IP:2377"
          ssh -tt -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$JOIN_IP "sudo apt-get update \
            && sudo apt-get install docker.io -y \
            && sudo systemctl start docker \
            && sudo systemctl enable docker \
            && echo $JOIN_TOKEN \
            && echo $SWARM_IP \
            && sudo docker swarm join --token $JOIN_TOKEN $SWARM_IP:2377"
      