name: CI

on:
  push:
    branches:
      - main

jobs:
  init_swarm:
    runs-on: ubuntu-latest
    outputs:
      join_token: ${{ steps.init_swarm.outputs.join_token}}
      swarm_ip: ${{ steps.init_swarm.outputs.swarm_ip }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Add SSH Keys
        run: |
          cd ~/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > "docker-swarm-ubuntu.pem"
          sudo chmod 400 "docker-swarm-ubuntu.pem"
      - name: Init Docker Swarm On Instance 1
        id: init_swarm
        run: |
          IPS="47.128.245.11,52.221.211.118"
          IFS=',' read -ra ADDR <<< "$IP"
          SWARM_IP=${ADDR[0]}
          ssh -tt -o StrictHostKeyChecking=no -i "docker-swarm-ubuntu.pem" ubuntu@$SWARM_IP << "EOF"
            sudo apt-get update
            sudo apt-get install docker.io -y
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo docker swarm init --advertise-addr=$SWARM_IP
          EOF
          JOIN_TOKEN=$(ssh -tt -o StrictHostKeyChecking=no -i "docker-swarm-ubuntu.pem" ubuntu@$SWARM_IP "sudo docker swarm join-token -q worker")
          echo "join_token=$JOIN_TOKEN" >> "$GITHUB_OUTPUT"
          echo "swarm_ip=$SWARM_IP" >> "$GITHUB_OUTPUT"

  join-swarm:
    needs: init_swarm
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH Keys
        run: |
          cd ~/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > "docker-swarm-ubuntu.pem"
          sudo chmod 400 "docker-swarm-ubuntu.pem"
      - name: Instance 2 joins Docker Swarm
        run: |
          IPS="47.128.245.11,52.221.211.118"
          IFS=',' read -ra ADDR <<< "$IP"
          SWARM_IP=${ADDR[0]}
          JOIN_IP=${ADDR[1]}
          JOIN_TOKEN="${{ needs.init_swarm.outputs.join_token }}"
          ssh -tt -o StrictHostKeyChecking=no -i "docker-swarm-ubuntu.pem" ubuntu@$JOIN_IP << "EOF"
            sudo apt-get update
            sudo apt-get install docker.io -y
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo docker swarm join --token $JOIN_TOKEN $SWARM_IP:2377
          EOF