name: CI

on:
  push:
    branches:
      - main

jobs:
  join-swarm:
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Instance 2 joins Docker Swarm
        id: join_swarm
        run: |
          IPS="54.169.115.66,13.212.83.159"
          IFS=',' read -ra ADDR <<< "$IPS"
          SWARM_IP=${ADDR[0]}
          JOIN_IP=${ADDR[1]}
          SWARM_USER="ubuntu"
          echo "swarm_info=$SWARM_IP,$SWARM_USER" >> "$GITHUB_OUTPUT"
          echo "$SWARM_IP,$SWARM_USER" > swarm_info.txt
          JOIN_TOKEN="SWMTKN-1-5b7g6enha5xudxg4epxkupe5zmm4s9vw6w7lnt33k43wkf83ns-efktnylkeqguuapusih49ig6d"
          FORMAT_TOKEN=$(echo $JOIN_TOKEN | tr -d '\n\r')
          ssh -tt -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$JOIN_IP "sudo apt-get update \
            && sudo apt-get install docker.io -y \
            && sudo systemctl start docker \
            && sudo systemctl enable docker \
            && echo $FORMAT_TOKEN \
            && echo $SWARM_IP \
            && sudo docker swarm join --token $FORMAT_TOKEN $SWARM_IP:2377"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Copy Docker Info to S3 Bucket
        run: |
          aws s3 cp swarm_info.txt s3://kha-app-s3/swarm_info/