name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terrafrom-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Set up Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Init Terraform
        run: terraform init
      - name: Download Terraform State from S3 Bucket
        run: |
          aws s3 cp s3://kha-app-s3/state/terraform.tfstate .
      - name: Destroy Terraform configuration
        run: terraform destroy -auto-approve
      - name: Delete Terraform State on S3 bucket
        run: |
          aws s3 rm s3://kha-app-s3/state/terraform.tfstate